# Generated by Django 3.1.6 on 2021-03-04 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('registration_starts', models.DateField(blank=True, null=True)),
                ('registration_end', models.DateField(blank=True, null=True)),
                ('submission_starts', models.DateField(blank=True)),
                ('submission_ends', models.DateField(blank=True, null=True)),
                ('max_members_per_team', models.IntegerField(null=True)),
                ('teams', models.ManyToManyField(blank=True, related_name='events_registered', to='accounts.Team')),
            ],
            options={
                'ordering': ('-registration_starts',),
            },
        ),
        migrations.CreateModel(
            name='SubTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('submission_done', models.BooleanField(default=False)),
                ('submission_link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_particiaptd', to='events.event')),
                ('members', models.ManyToManyField(related_name='subteams', to='accounts.Profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subteams', to='accounts.team')),
            ],
        ),
    ]
