# Generated by Django 3.1.6 on 2021-02-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('registration_starts', models.DateField(blank=True)),
                ('submission_starts', models.DateField(blank=True)),
                ('submission_ends', models.DateField(blank=True)),
                ('max_members_per_team', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('-registration_starts',),
            },
        ),
    ]
