# Generated by Django 3.1.6 on 2021-03-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='max_members_per_team',
            new_name='max_per_team',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_starts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='submission_ends',
        ),
        migrations.RemoveField(
            model_name='event',
            name='submission_starts',
        ),
        migrations.AddField(
            model_name='event',
            name='min_per_team',
            field=models.IntegerField(null=True),
        ),
    ]
