# Generated by Django 3.1.6 on 2021-02-23 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210223_0447'),
        ('events', '0002_subteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(related_name='events_registered', to='accounts.Team'),
        ),
        migrations.AddField(
            model_name='subteam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subteam',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subteam',
            name='submission_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subteam',
            name='submission_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subteam',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_starts',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='submission_ends',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_particiaptd', to='events.event'),
        ),
    ]
