# Generated by Django 3.1.6 on 2021-03-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210305_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='teams',
        ),
    ]
