# Generated by Django 3.1.6 on 2021-03-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subteam',
            name='event_name',
        ),
    ]
