# Generated by Django 3.1.6 on 2021-02-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210223_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subteam',
            name='name',
        ),
    ]
