# Generated by Django 3.1.6 on 2021-03-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_subteam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subteam',
            name='event_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
