# Generated by Django 3.1.6 on 2021-02-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210223_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='descripion',
            field=models.TextField(blank=True),
        ),
    ]
