# Generated by Django 3.1.6 on 2021-02-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team_descripion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='descripion',
            new_name='description',
        ),
    ]
